package br.lumi.server.enuns;

public enum EPais {

	AFEGANISTAO("Afeganistão"),
	AFRICADOSUL("Africa do Sul"),
	AKROTIRI("Akrotiri"),
	ALBANIA("Albânia"),
	ALEMANHA("Alemanha"),
	ANDORRA("Andorra"),
	ANGOLA("Angola"),
	ANGUILA("Anguila"),
	ANTARCTIDA("Antárctida"),
	ANTIGUAEBARBUDA("Antágua e Barbuda"),
	ANTILHASNEERLANDESAS("Antilhas Neerlandesas"),
	ARABIASAUDITA("Arábia Saudita"),
	ARCTICOCEAN("Arctic Ocean"),
	ARGELIA("Argélia"),
	ARGENTINA("Argentina"),
	ARMENIA("Armênia"),
	ARUBA("Aruba"),
	ASHMOREANDCARTIERISLANDS("Ashmore and Cartier Islands"),
	ATLANTICOCEAN("Atlantic Ocean"),
	AUSTRALIA("Austrália"),
	AUSTRIA("Austria"),
	AZERBAIJAO("Azerbaijão"),
	BAAMAS("Baamas"),
	BANGLADECHE("Bangladeche"),
	BARBADOS("Barbados"),
	BAREM("Barêm"),
	BELGICA("Bélgica"),
	BELIZE("Belize"),
	BENIM("Benim"),
	BERMUDAS("Bermudas"),
	BIELORRUSSIA("Bielorrússia"),
	BIRMANIA("Birmânia"),
	BOLIVIA("Bolívia"),
	BOSNIAEHERZEGOVINA("Bósni e Herzegovina"),
	BOTSUANA("Botsuana"),
	BRASIL("Brasil"),
	BRUNEI("Brunei"),
	BULGARIA("Bulgária"),
	BURQUINAFASO("Burquina Faso"),
	BURUNDI("Burúndi"),
	BUTAO("Butão"),
	CABOVERDE("Cabo Verde"),
	CAMAROES("Camarões"),
	CAMBOJA("Camboja"),
	CANADA("Canadá"),
	CATAR("Catar"),
	CAZAQUISTAO("Cazaquistão"),
	CHADE("Chade"),
	CHILE("Chile"),
	CHINA("China"),
	CHIPRE("Chipre"),
	CLIPPERTONISLAND("Clipperton Island"),
	COLOMBIA("Colômbia"),
	COMORES("Comores"),
	CONGOBRAZZAVILLE("Congo-Brazzaville"),
	CONGOKINSHASA("Congo-Kinshasa"),
	CORALSEAISLANDS("Coral Sea Islands"),
	COREIADONORTE("Coreia do Norte"),
	COREIADOSUL("Coreia do Sul"),
	COSTADOMARFIM("Costa do Marfim"),
	COSTARICA("Costa Rica"),
	CROACIA("Croácia"),
	CUBA("Cuba"),
	DHEKELIA("Dhekelia"),
	DINAMARCA("Dinamarca"),
	DOMINICA("Domínica"),
	EGIPTO("Egipto"),
	EMIRATOSARABESUNIDOS("Emiratos Arabes Unidos"),
	EQUADOR("Equador"),
	ERITREIA("Eritreia"),
	ESLOVAQUIA("Eslováquia"),
	ESLOVENIA("Eslovênia"),
	ESPANHA("Espanha"),
	ESTADOSUNIDOS("Estados Unidos"),
	ESTONIA("Estônia"),
	ETIOPIA("Etiópia"),
	FAROE("Faroé"),
	FIJI("Fiji"),
	FILIPINAS("Filipinas"),
	FINLANDIA("Finlândia"),
	FRANCA("França"),
	GABAO("Gabão"),
	GAMBIA("Gambia"),
	GANA("Gana"),
	GAZASTRIP("Gaza Strip"),
	GEORGIA("Geórgia"),
	GEORGIADOSULESANDWICHDOSUL("Geórgia do Sul e Sandwich do Sul"),
	GIBRALTAR("Gibraltar"),
	GRANADA("Granada"),
	GRECIA("Grécia"),
	GRONELANDIA("Gronelândia"),
	GUAME("Guame"),
	GUATEMALA("Guatemala"),
	GUERNSEY("Guernsey"),
	GUIANA("Guiana"),
	GUINE("Guiné"),
	GUINEEQUATORIAL("Guiné Equatorial"),
	GUINEBISSAU("Guiné-Bissau"),
	HAITI("Haiti"),
	HONDURAS("Honduras"),
	HONGKONG("Hong Kong"),
	HUNGRIA("Hungria"),
	IEMEN("Iemen"),
	ILHABOUVET("Ilha Bouvet"),
	ILHADONATAL("Ilha do Natal"),
	ILHANORFOLK("Ilha Norfolk"),
	ILHASCAIMAO("Ilhas Caimão"),
	ILHASCOOK("Ilhas Cook"),
	ILHASDOSCOCOS("Ilhas dos Cocos"),
	ILHASFALKLAND("Ilhas Falkland"),
	ILHASHEARDEMCDONALD("Ilhas Heard e McDonald"),
	ILHASMARSHALL("Ilhas Marshall"),
	ILHASSALOMAO("Ilhas Salomão"),
	ILHASTURCASECAICOS("Ilhas Turcas e Caicos"),
	ILHASVIRGENSAMERICANAS("Ilhas Virgens Americanas"),
	ILHASVIRGENSBRITANICAS("Ilhas Virgens Britânicas"),
	INDIA("India"),
	INDIANOCEAN("Indian Ocean"),
	INDONESIA("Indonésia"),
	IRA("Irã"),
	IRAQUE("Iraque"),
	IRLANDA("Irlanda"),
	ISLANDIA("Islândia"),
	ISRAEL("Israel"),
	ITALIA("Itália"),
	JAMAICA("Jamaica"),
	JANMAYEN("Jan Mayen"),
	JAPAO("Japão"),
	JERSEY("Jersey"),
	JIBUTI("Jibuti"),
	JORDANIA("Jordânia"),
	KUWAIT("Kuwait"),
	LAOS("Laos"),
	LESOTO("Lesoto"),
	LETONIA("Letônia"),
	LIBANO("Líbano"),
	LIBERIA("Libéria"),
	LIBIA("Líbia"),
	LISTENSTAINE("Listenstaine"),
	LITUANIA("Lituânia"),
	LUXEMBURGO("Luxemburgo"),
	MACAU("Macau"),
	MACEDONIA("Macedônia"),
	MADAGASCAR("Madagascar"),
	MALASIA("Malâsia"),
	MALAVI("Malâvi"),
	MALDIVAS("Maldivas"),
	MALI("Mali"),
	MALTA("Malta"),
	MANISLEOF("Man, Isle of"),
	MARIANASDONORTE("Marianas do Norte"),
	MARROCOS("Marrocos"),
	MAURICIA("Maur�cia"),
	MAURITANIA("Maurit�nia"),
	MAYOTTE("Mayotte"),
	MEXICO("México"),
	MICRONESIA("Micron�sia"),
	MOCAMBIQUE("Moçambique"),
	MOLDAVIA("Moldávia"),
	MONACO("M�naco"),
	MONGOLIA("Mongólia"),
	MONSERRATE("Monserrate"),
	MONTENEGRO("Montenegro"),
	MUNDO("Mundo"),
	NAMIBIA("Namíbia"),
	NAURU("Nauru"),
	NAVASSAISLAND("Navassa Island"),
	NEPAL("Nepal"),
	NICARAGUA("Nicarágua"),
	NIGER("Níger"),
	NIGERIA("Nigéria"),
	NIUE("Niue"),
	NORUEGA("Noruega"),
	NOVACALEDONIA("Nova Caledônia"),
	NOVAZELANDIA("Nova Zelândia"),
	OMA("Omá"),
	PACIFICOCEAN("Pacific Ocean"),
	PAISESBAIXOS("Países Baixos"),
	PALAU("Palau"),
	PANAMA("Panamá"),
	PAPUANOVAGUINE("Papua-Nova Guiné"),
	PAQUISTAO("Paquistão"),
	PARACELISLANDS("Paracel Islands"),
	PARAGUAI("Paraguai"),
	PERU("Peru"),
	PITCAIRN("Pitcairn"),
	POLINESIAFRANCESA("Polinésia Francesa"),
	POLONIA("Polônia"),
	PORTORICO("Porto Rico"),
	PORTUGAL("Portugal"),
	QUENIA("Quênia"),
	QUIRGUIZISTAO("Quirguizistão"),
	QUIRIBATI("Quiribati"),
	REINOUNIDO("Reino Unido"),
	REPUBLICACENTROAFRICANA("Republica Centro-Africana"),
	REPUBLICACHECA("Republica Checa"),
	REPUBLICADOMINICANA("Republica Dominicana"),
	ROMENIA("Romênia"),
	RUANDA("Ruanda"),
	RUSSIA("Russia"),
	SALVADOR("Salvador"),
	SAMOA("Samoa"),
	SAMOAAMERICANA("Samoa Americana"),
	SANTAHELENA("Santa Helena"),
	SANTALUCIA("Santa Lùcia"),
	SAOCRISTOVAOENEVES("São Cristóvão e Neves"),
	SAOMARINHO("São Marinho"),
	SAOPEDROEMIQUELON("São Pedro e Miquelon"),
	SAOTOMEEPRINCIPE("São Tom� e Príncipe"),
	SAOVICENTEEGRANADINAS("São Vicente e Granadinas"),
	SARAOCIDENTAL("Sara Ocidental"),
	SEICHELES("Seicheles"),
	SENEGAL("Senegal"),
	SERRALEOA("Serra Leoa"),
	SERVIA("Sérvia"),
	SINGAPURA("Singapura"),
	SIRIA("Síria"),
	SOMALIA("Somália"),
	SOUTHERNOCEAN("Southern Ocean"),
	SPRATLYISLANDS("Spratly Islands"),
	SRILANCA("Sri Lanca"),
	SUAZILANDIA("Suazil�ndia"),
	SUDAO("Sudão"),
	SUECIA("Suécia"),
	SUICA("Suíça"),
	SURINAME("Suriname"),
	SVALBARDEJANMAYEN("Svalbard e Jan Mayen"),
	TAILANDIA("Tailândia"),
	TAIWAN("Taiwan"),
	TAJIQUISTAO("Tajiquistão"),
	TANZANIA("Tanzânia"),
	TERRITORIOBRITANICODOOCEANOINDICO("Território Britânico do Oceano Indico"),
	TERRITORIOSAUSTRAISFRANCESES("Territórios Austrais Franceses"),
	TIMORLESTE("Timor Leste"),
	TOGO("Togo"),
	TOKELAU("Tokelau"),
	TONGA("Tonga"),
	TRINDADEETOBAGO("Trindade e Tobago"),
	TUNISIA("Tunísia"),
	TURQUEMENISTAO("Turquemenistão"),
	TURQUIA("Turquia"),
	TUVALU("Tuvalu"),
	UCRANIA("Ucrânia"),
	UGANDA("Uganda"),
	UNIAOEUROPEIA("União Europeia"),
	URUGUAI("Uruguai"),
	USBEQUISTAO("Usbequistão"),
	VANUATU("Vanuatu"),
	VATICANO("Vaticano"),
	VENEZUELA("Venezuela"),
	VIETNAME("Vietname"),
	WAKEISLAND("Wake Island"),
	WALLISEFUTUNA("Wallis e Futuna"),
	WESTBANK("West Bank"),
	ZAMBIA("Zâmbia"),
	ZIMBABUE("Zimbabuá"),

	;

	private String pais;

	private EPais(String pais) {
		this.pais = pais;
	}

	/**
	 * @return the pais
	 */
	public String getPais() {
		return pais;
	}

	@Override
	public String toString() {
		return getPais();
	}
	
}
